version: "1"
services:
- type: web
  name: json_api_server
  runtime: python
  repo: https://github.com/providedtroubleshoot/json_api_server
  plan: free
  region: frankfurt

  buildCommand: "pip install -r requirements.txt"
  startCommand: "python app.py"

  envVars:
  - key: PROXY_URL
    sync: false
  - key: FIRESTORE_KEY
    sync: false
  - key: GITHUB_TOKEN
    sync: false

  autoDeployTrigger: "off"