version: "1"
services:
- type: web
  name: json_api_server
  env: docker
  repo: https://github.com/providedtroubleshoot/json_api_server
  plan: free
  region: frankfurt

  envVars:
  - key: PROXY_URL
    sync: false
  - key: FIRESTORE_KEY
    sync: false
  - key: GITHUB_TOKEN
    sync: false

  autoDeployTrigger: "off"